### ISSUE TITLE
Can Stable Audio generate longer duration tracks

### ISSUE THREAD

**Issue by Saltb0xApps** [yukara-ikemiya/friendly-stable-audio-tools#8]
With enough finetuning on longer tracks, would it be possible to do "continuation" or generate tracks longer than its default limit in one shot?

**Comment by yukara-ikemiya** [comment]
Hi, I think the answer is partially yes.

Regarding `continuation`, it would be difficult or require large modifications of codes to fine-tune pre-trained models like StableAudioOpen (SA-Open). Continuation requires `inpainting/outpainting`  based on the already generated section as a condition, but models like SA-Open (or StableAudio 2.0) do not have this conditionality in their design. Therefore, fine-tuning them in their current form would be difficult.

Regarding `longer track generation`, I believe it can be achieved through fine-tuning models like SA-Open. In these models, positional embeddings for the input sequence are implemented using `RotaryEmbedding`, allowing fine-tuning with longer audio than what was used during pretraining. With enough data for fine-tuning, the model should be optimized to generate tracks of the new length.

https://github.com/yukara-ikemiya/friendly-stable-audio-tools/blob/8bcff7280ad372e99d79b18c5b395a5b6d9c5284/stable_audio_tools/models/transformer.py#L99
