### ISSUE TITLE
Is the rectified_flow implementation correct?

### ISSUE THREAD

**Issue by 980202006** [yukara-ikemiya/friendly-stable-audio-tools#9]
![image](https://github.com/user-attachments/assets/6d64495e-402b-4b23-97ec-26bcdcdaaf3e)
![image](https://github.com/user-attachments/assets/9ec108d3-4bf6-4fce-9571-f0ad6a14bb0a)
![image](https://github.com/user-attachments/assets/ac7771de-e700-4bfa-a006-20ec339d6389)
Referring to the official implementation, should vt be ground_truth minus noise?

**Comment by 980202006** [comment]
https://github.com/gnobitab/RectifiedFlow/tree/main

**Comment by yukara-ikemiya** [comment]
This is just a target of prediction by a model, and predicting `x0 - xT` and `xT - x0` is mathmatically the same.
What we have to keep in mind during implementation is to ensure the correct correspondence between the sign of the prediction and the sign of the values added during inference (sampling).

In this repository, the sampling of Rectified Flow is implemented here, and this corresponds to the definition of prediction target.
https://github.com/yukara-ikemiya/friendly-stable-audio-tools/blob/8bcff7280ad372e99d79b18c5b395a5b6d9c5284/stable_audio_tools/inference/sampling.py#L50

**Comment by 980202006** [comment]
Thank you for your reply.I got it!

**Comment by 980202006** [comment]
I saw that the library uses the discret euler solver, and some use torchdiffeq's odeint. Are there any differences between them?Is there any tensorboard or loss curve for training rectified_flow? @yukara-ikemiya

**Comment by yukara-ikemiya** [comment]
The `torchdiffeq` seems to provide a very general framework for ODE solvers.
If the repositories you mentioned use `Euler` solver in torchdiffeq, it should be equivalent to the implementation in this repository.
https://github.com/rtqichen/torchdiffeq/blob/a88aac53cae738addee44251288ce5be9a018af3/torchdiffeq/_impl/fixed_grid.py#L6

**Comment by 980202006** [comment]
Thank you!
